image: mcr.microsoft.com/dotnet/sdk:6.0-focal

stages:
  - build
  - test

build:
  stage: build
  script:
    - dotnet restore src/common/InstaCrafter.Extensions/InstaCrafter.Extensions.csproj --locked-mode
    - dotnet build src/common/InstaCrafter.Extensions/InstaCrafter.Extensions.csproj -c Release --no-restore --no-dependencies
test:
  stage: test
  before_script:
    - apt update && apt install -y libc-dev libgdiplus
    - dotnet tool install dotnet-reportgenerator-globaltool --tool-path tools
    - dotnet tool install --global coverlet.console
    - export PATH="$PATH:/root/.dotnet/tools"
  script:
    - dotnet build src/tests/InstaCrafter.Extensions.Tests/InstaCrafter.Extensions.Tests.csproj
    - dotnet test src/tests/InstaCrafter.Extensions.Tests/InstaCrafter.Extensions.Tests.csproj /p:CollectCoverage=true --no-build
    - reportgenerator "-reports:src/tests/InstaCrafter.Extensions.Tests/TestResults/*/coverage.cobertura.xml" "-targetdir:Reports/Coverage/Text" -reportTypes:TextSummary
    - reportgenerator "-reports:src/tests/InstaCrafter.Extensions.Tests/TestResults/*/coverage.cobertura.xml" "-targetdir:Reports/Coverage/Html" -reportTypes:Html
    - cat Reports/Coverage/Text/Summary.txt
  coverage: /^\s*Line coverage:\s*\d+.\d+\%$/
  artifacts:
    when: always
    paths:
      - Reports/Coverage
