image: mcr.microsoft.com/dotnet/sdk:6.0-focal

stages:
  - build

build:
  stage: build
  script:
    - dotnet restore src/InstaCrafter.sln --locked-mode
    - dotnet build src/InstaCrafter.sln -c Release --no-restore --no-dependencies