image: mcr.microsoft.com/dotnet/sdk:6.0-focal

stages:
  - build

build:
  stage: build
  script:
    - dotnet restore src/common/InstaCrafert.Extensions/InstaCrafert.Extensions.csproj --locked-mode
    - dotnet build src/common/InstaCrafert.Extensions/InstaCrafert.Extensions.csproj -c Release --no-restore --no-dependencies