stages:
  - build-net
  - build-app
  - test-net
  - test-app

cache:
  paths:
    - src/clients/react-app/node_modules/

build-net:
  stage: build-net
  image: mcr.microsoft.com/dotnet/sdk:5.0-bullseye-slim
  script:
    - apt update -y -q && apt install -y -q libc-dev libgdiplus
    - export PATH="$PATH:/root/.dotnet/tools"
    - dotnet nuget add source "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/packages/nuget/index.json" --name gitlab --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
    - dotnet nuget add source "$CI_SERVER_URL/api/v4/projects/8/packages/nuget/index.json" --name cozybus --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
    - dotnet nuget add source "$CI_SERVER_URL/api/v4/projects/14/packages/nuget/index.json" --name instasharper --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
    - dotnet restore src/InstaCrafter.sln
    - dotnet build src/InstaCrafter.sln -c Release

test-net:
  stage: test-net
  image: mcr.microsoft.com/dotnet/sdk:5.0-bullseye-slim
  script:
    - apt update -y -q && apt install -y -q libc-dev libgdiplus
    - export PATH="$PATH:/root/.dotnet/tools"
    - dotnet nuget add source "$CI_SERVER_URL/api/v4/projects/14/packages/nuget/index.json" --name cozybus --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
    - dotnet tool install -g dotnet-reportgenerator-globaltool
    - dotnet tool install --global coverlet.console
    - dotnet test src/tests/InstaCrafter.Extensions.Tests/InstaCrafter.Extensions.Tests.csproj --collect:"XPlat Code Coverage"
    - reportgenerator "-reports:src/tests/InstaCrafter.Extensions.Tests/TestResults/*/coverage.cobertura.xml" "-targetdir:Reports/Coverage/Text" -reportTypes:TextSummary
    - reportgenerator "-reports:src/tests/InstaCrafter.Extensions.Tests/TestResults/*/coverage.cobertura.xml" "-targetdir:Reports/Coverage/Html" -reportTypes:Html
    - cat Reports/Coverage/Text/Summary.txt
  coverage: /^\s*Line coverage:\s*\d+.\d+\%$/

build-app:
  stage: build-app
  image: node
  script:
    - cd src/clients/react-app/
    - npm --force install -g yarn
    - yarn --non-interactive
    - yarn build --non-interactive

test-app:
  stage: test-app
  image: node
  script:
    - cd src/clients/react-app/
    - npm --force install -g yarn
    - yarn --non-interactive
    - yarn build --non-interactive
    - CI=true yarn test

