language: csharp
solution: InstaCrafter.sln
dotnet: 1.0.0-preview2-003121
sudo: required
os: linux
dist: trusty

script:
  # dotnet info
  - dotnet --info
  # Run dotnet new 
  - dotnet restore
  - cd src/InstaCrafter.DataStore
  - dotnet --verbose build
  - dotnet publish
  - cd ../InstaCrafter.Classes
  - dotnet --verbose build
  - cd ../InstaCrafter.Tests
  - dotnet --verbose build