language: csharp
solution: InstaCrafter.sln
dotnet: 1.0.0-preview2-003121
	  
script:
  # dotnet info
  - dotnet --info
  # Run dotnet new 
  - dotnet restore
  - cd src/InstaCrafter
  - dotnet --verbose build
  - dotnet publish
  - cd ../InstaCrafter.Worker
  - dotnet --verbose build
  - dotnet publish
  - cd ../InstaCrafter.Classes
  - dotnet --verbose build
  - dotnet publish
  - cd ../InstaCrafter.Core
  - dotnet --verbose build
  - dotnet publish