version: 1.0.{build}
os: Visual Studio 2015

build_script:
  # dotnet info
  - ps: dotnet --info
  # Run dotnet new 
  - ps: dotnet restore
  - ps: cd src/InstaCrafter
  - ps: dotnet --verbose build
  - ps: dotnet --verbose publish
  - ps: cd ../InstaCrafter.Worker
  - ps: dotnet --verbose build
  - ps: dotnet --verbose publish
  - ps: cd ../InstaCrafter.Classes
  - ps: dotnet --verbose build
  - ps dotnet --verbose publish
  - ps: cd ../InstaCrafter.Core
  - ps: dotnet --verbose build
  - ps: dotnet --verbose publish
  
test: off 
