version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
configuration: Release
platform: Any CPU
init:
- cmd: git config --global core.autocrlf true
environment:
  website_name: aspnetcorespa
  website_psw:
    secure: UBm/tZDG4wmtrN6phRaqCBGkZqkpXWIWqMJJFxx6Zknn5imdJssw+9ZZPnT9iriMs364WsFtpNqDi7/sgDt5cQ==
  nodejs_version: "6.6.0"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm typings
  - ps: $env:path = $env:appdata + "\npm;" + $env:path
  - npm install
  - typings install

test_script:
  # Output useful info for debugging.
  - node --version && npm --version
  - node -e 'console.log(process.env);'
  # - cmd: npm test

cache:
  - node_modules -> package.json                                        # local npm modules

before_build:
  - npm run build:prod                                           # Client production artefacts
  - dotnet restore
build:
  project: OrdersStorage.xproj
  publish_wap: true
  verbosity: minimal

after_build:
- cmd: >-
    dotnet publish .\ --output %appveyor_build_folder%\dist
    dotnet publish-iis --publish-folder %appveyor_build_folder%\dist --framework %publish:FullTargetFramework%

artifacts:
- path: dist
  name: web-app
