version: 1.0.{build}
os: Visual Studio 2017
platform: Any CPU

environment:
    nodejs_version: "6"
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

install:
    - ps: Install-Product node $env:nodejs_version
    - npm install

build_script:
  - ps: nuget sources add -Name MyGetSharper -Source https://www.myget.org/F/instasharper-develop/api/v3/index.json
  # dotnet info
  - ps: dotnet --info
  # Run dotnet new 
  - ps: dotnet restore
  - ps: cd src/InstaCrafter.DataStore
  - ps: dotnet build
  - ps: cd ../InstaCrafter.Classes
  - ps: dotnet build
  - ps: cd ../InstaCrafter.Web
  - ps: npm install --no-optional
  - ps: dotnet build
  
test: off 
