version: 1.0.{build}
os: Visual Studio 2017
platform: Any CPU

build_script:
  - ps: nuget sources add -Name MyGetSharper -Source https://www.myget.org/F/instasharper-develop/api/v3/index.json
  # dotnet info
  - ps: dotnet --info
  # Run dotnet new 
  - ps: dotnet restore
  - ps: cd src/InstaCrafter.DataStore
  - ps: dotnet build
  - ps: cd ../InstaCrafter.Classes
  - ps: dotnet --verbose build
  - ps: cd ../InstaCrafter.Web
  - ps: dotnet build
  
test: off 
