version: 1.0.{build}
os: Visual Studio 2015
platform: Any CPU

build_script:
  # dotnet info
  - ps: dotnet --info
  # Run dotnet new 
  - ps: dotnet restore
  - ps: cd src/InstaCrafter.DataStore
  - ps: dotnet --verbose build
  - ps: dotnet publish
  - ps: cd ../InstaCrafter.Classes
  - ps: dotnet --verbose build
  - ps: cd ../InstaCrafter.Tests
  - ps: dotnet --verbose build
  
test: off 
