version: '3.4'

services:
  instacrafter-api-gateway:
    image: instacrafter-api-gateway
    build:
      context: .
      network: host
      dockerfile: src/services/InstaCrafter.ApiGateway/Dockerfile
    restart: on-failure
    deploy:
      replicas: 1
    networks:
      - main-network
    expose:
      - "8080"
    ports:
      - "8080:8080"
  instacrafter-identity:
    image: instacrafter-identity
    build:
      context: .
      network: host
      dockerfile: src/services/identity/InstaCrafter.Identity/Dockerfile
    restart: on-failure
    deploy:
      replicas: 1
    networks:
      - main-network
    expose:
      - "8081"


networks:
  main-network:
    driver: bridge