// <auto-generated />
using System;
using InstaCrafter.PostService.DataProvider.PostgreSQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace InstaCrafter.PostService.Migrations
{
    [DbContext(typeof(PostgreSqlDatabaseContext))]
    partial class PostgreSqlDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "3.0.0-preview3.19153.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("InstaCrafter.PostService.DtoModels.InstagramImageDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Height");

                    b.Property<string>("Path");

                    b.Property<long?>("PostId");

                    b.Property<string>("URI");

                    b.Property<DateTime>("UpdatedTimestamp");

                    b.Property<int>("Width");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("InstaImages");
                });

            modelBuilder.Entity("InstaCrafter.PostService.DtoModels.InstagramPostDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClientCacheKey");

                    b.Property<string>("Code");

                    b.Property<string>("CommentsCount");

                    b.Property<DateTime>("DeviceTimeStamp");

                    b.Property<string>("FilterType");

                    b.Property<bool>("HasAudio");

                    b.Property<bool>("HasLiked");

                    b.Property<string>("Height");

                    b.Property<string>("InstaIdentifier");

                    b.Property<int>("LikesCount");

                    b.Property<int>("MediaType");

                    b.Property<string>("NextMaxId");

                    b.Property<bool>("PhotoOfYou");

                    b.Property<string>("Pk");

                    b.Property<DateTime>("TakenAt");

                    b.Property<string>("TrackingToken");

                    b.Property<DateTime>("UpdatedTimestamp");

                    b.Property<long>("UserId");

                    b.Property<int>("ViewCount");

                    b.Property<int>("Width");

                    b.HasKey("Id");

                    b.ToTable("InstaPosts");
                });

            modelBuilder.Entity("InstaCrafter.PostService.DtoModels.InstagramVideoDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Height");

                    b.Property<string>("Path");

                    b.Property<long?>("PostId");

                    b.Property<int>("Type");

                    b.Property<DateTime>("UpdatedTimestamp");

                    b.Property<string>("Url");

                    b.Property<int>("Width");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("InstaVideos");
                });

            modelBuilder.Entity("InstaCrafter.PostService.DtoModels.InstagramImageDto", b =>
                {
                    b.HasOne("InstaCrafter.PostService.DtoModels.InstagramPostDto", "Post")
                        .WithMany("Images")
                        .HasForeignKey("PostId");
                });

            modelBuilder.Entity("InstaCrafter.PostService.DtoModels.InstagramVideoDto", b =>
                {
                    b.HasOne("InstaCrafter.PostService.DtoModels.InstagramPostDto", "Post")
                        .WithMany("Videos")
                        .HasForeignKey("PostId");
                });
#pragma warning restore 612, 618
        }
    }
}
