// <auto-generated />
using System;
using InstaCrafter.UserService.DataProvider.PostgreSQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace InstaCrafter.UserService.Migrations
{
    [DbContext(typeof(PostgreSqlDatabaseContext))]
    partial class PostgreSqlDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "3.0.0-preview3.19153.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("InstaCrafter.UserService.DtoModels.InstagramUserDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("FollowersCount");

                    b.Property<string>("FollowersCountByLine");

                    b.Property<string>("FullName");

                    b.Property<bool>("HasAnonymousProfilePicture");

                    b.Property<bool>("IsPrivate");

                    b.Property<bool>("IsVerified");

                    b.Property<int>("MutualFollowers");

                    b.Property<long>("Pk");

                    b.Property<string>("ProfilePicture");

                    b.Property<string>("SearchSocialContext");

                    b.Property<string>("SocialContext");

                    b.Property<int>("UnseenCount");

                    b.Property<DateTime>("UpdatedTimestamp");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("InstaUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
