name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    types: [ closed ]
    branches: [ master ]

env:
  USER: ${{ secrets.USER }}
  PASS: ${{ secrets.PASS }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
          include-prerelease: true
      - name: Add nuget Cozy
        run: dotnet nuget add source "https://git.codegarage.ru/api/v4/projects/2/packages/nuget/index.json" --name cozybus --username $USER --password $PASS --store-password-in-clear-text
      - name: Add nuget Instasharper
        run: dotnet nuget add source "https://git.codegarage.ru/api/v4/projects/4/packages/nuget/index.json" --name instasharper --username $USER --password $PASS --store-password-in-clear-text
      - name: Restore
        run: dotnet restore src/InstaCrafter.sln
      - name: Build
        run: dotnet build src/InstaCrafter.sln -c Release
